//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Data .
        /// </summary>
        public static string areaDataList {
            get {
                return ResourceManager.GetString("areaDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: Pokémon Black .
        /// </summary>
        public static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: Pokémon Black 2 .
        /// </summary>
        public static string black2 {
            get {
                return ResourceManager.GetString("black2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black 2.
        /// </summary>
        public static string black2b {
            get {
                return ResourceManager.GetString("black2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string blackb {
            get {
                return ResourceManager.GetString("blackb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building .
        /// </summary>
        public static string building {
            get {
                return ResourceManager.GetString("building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Pack .
        /// </summary>
        public static string buildingPackList {
            get {
                return ResourceManager.GetString("buildingPackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building files (*.bld)|*.bld.
        /// </summary>
        public static string buildingsFile {
            get {
                return ResourceManager.GetString("buildingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: Pokémon Diamond .
        /// </summary>
        public static string diamond {
            get {
                return ResourceManager.GetString("diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        public static string diamondb {
            get {
                return ResourceManager.GetString("diamondb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded textures have been automatically removed from model.
        /// </summary>
        public static string embeddedTextures {
            get {
                return ResourceManager.GetString("embeddedTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event .
        /// </summary>
        public static string eventList {
            get {
                return ResourceManager.GetString("eventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Buildings Section as....
        /// </summary>
        public static string exportBuildings {
            get {
                return ResourceManager.GetString("exportBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Model Section as....
        /// </summary>
        public static string exportModel {
            get {
                return ResourceManager.GetString("exportModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export model as....
        /// </summary>
        public static string exportModelBld {
            get {
                return ResourceManager.GetString("exportModelBld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Move Permissions Section as....
        /// </summary>
        public static string exportMove {
            get {
                return ResourceManager.GetString("exportMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export sequence file as....
        /// </summary>
        public static string exportSSEQ {
            get {
                return ResourceManager.GetString("exportSSEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Terrain Section as....
        /// </summary>
        public static string exportTerrain {
            get {
                return ResourceManager.GetString("exportTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tileset as....
        /// </summary>
        public static string exportTileset {
            get {
                return ResourceManager.GetString("exportTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting packages....
        /// </summary>
        public static string extractPackage {
            get {
                return ResourceManager.GetString("extractPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string flags {
            get {
                return ResourceManager.GetString("flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Mode.
        /// </summary>
        public static string followMode {
            get {
                return ResourceManager.GetString("followMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (FRA).
        /// </summary>
        public static string fra {
            get {
                return ResourceManager.GetString("fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture .
        /// </summary>
        public static string furniture {
            get {
                return ResourceManager.GetString("furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GER).
        /// </summary>
        public static string ger {
            get {
                return ResourceManager.GetString("ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Headers Found: .
        /// </summary>
        public static string headersFound {
            get {
                return ResourceManager.GetString("headersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers were saved successfully.
        /// </summary>
        public static string headersSaved {
            get {
                return ResourceManager.GetString("headersSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: Pokémon HeartGold .
        /// </summary>
        public static string heartgold {
            get {
                return ResourceManager.GetString("heartgold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeartGold.
        /// </summary>
        public static string heartgoldb {
            get {
                return ResourceManager.GetString("heartgoldb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a buildings file to import.
        /// </summary>
        public static string importBuildings {
            get {
                return ResourceManager.GetString("importBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a model file to import.
        /// </summary>
        public static string importModel {
            get {
                return ResourceManager.GetString("importModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo DS Model files (*.nsbmd)|*.nsbmd.
        /// </summary>
        public static string importModelFile {
            get {
                return ResourceManager.GetString("importModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a move permissions file to import.
        /// </summary>
        public static string importMove {
            get {
                return ResourceManager.GetString("importMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a terrain file to import.
        /// </summary>
        public static string importTerrain {
            get {
                return ResourceManager.GetString("importTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tileset....
        /// </summary>
        public static string importTileset {
            get {
                return ResourceManager.GetString("importTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded Textures.
        /// </summary>
        public static string internalTextures {
            get {
                return ResourceManager.GetString("internalTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file. Operation aborted..
        /// </summary>
        public static string invalidFile {
            get {
                return ResourceManager.GetString("invalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ITA).
        /// </summary>
        public static string ita {
            get {
                return ResourceManager.GetString("ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (JAP).
        /// </summary>
        public static string jap {
            get {
                return ResourceManager.GetString("jap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (KOR).
        /// </summary>
        public static string kor {
            get {
                return ResourceManager.GetString("kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted data has been found for this ROM. Do you want to load it instead?.
        /// </summary>
        public static string lastROM {
            get {
                return ResourceManager.GetString("lastROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading map headers....
        /// </summary>
        public static string loadingHeaders {
            get {
                return ResourceManager.GetString("loadingHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ROM....
        /// </summary>
        public static string loadingROM {
            get {
                return ResourceManager.GetString("loadingROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Files.
        /// </summary>
        public static string mapFiles {
            get {
                return ResourceManager.GetString("mapFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Headers.
        /// </summary>
        public static string mapHeaders {
            get {
                return ResourceManager.GetString("mapHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map was saved successfully.
        /// </summary>
        public static string mapSaved {
            get {
                return ResourceManager.GetString("mapSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix .
        /// </summary>
        public static string matrix {
            get {
                return ResourceManager.GetString("matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map matrix was saved successfully.
        /// </summary>
        public static string matrixSaved {
            get {
                return ResourceManager.GetString("matrixSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo DS Model files (*.nsbmd)|*.nsbmd|Wavefront OBJ Model files (*.obj)|*.obj.
        /// </summary>
        public static string modelFile {
            get {
                return ResourceManager.GetString("modelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Permissions files (*.per)|*.per.
        /// </summary>
        public static string moveFile {
            get {
                return ResourceManager.GetString("moveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Frame.
        /// </summary>
        public static string nameFrame {
            get {
                return ResourceManager.GetString("nameFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Style.
        /// </summary>
        public static string nameStyle {
            get {
                return ResourceManager.GetString("nameStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo DS ROM files (*.nds)|*.nds.
        /// </summary>
        public static string ndsROM {
            get {
                return ResourceManager.GetString("ndsROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overworld .
        /// </summary>
        public static string overworld {
            get {
                return ResourceManager.GetString("overworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: Pokémon Pearl .
        /// </summary>
        public static string pearl {
            get {
                return ResourceManager.GetString("pearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearl.
        /// </summary>
        public static string pearlb {
            get {
                return ResourceManager.GetString("pearlb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: Pokémon Platinum .
        /// </summary>
        public static string platinum {
            get {
                return ResourceManager.GetString("platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string platinumb {
            get {
                return ResourceManager.GetString("platinumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading map data....
        /// </summary>
        public static string readingMap {
            get {
                return ResourceManager.GetString("readingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading matrix data....
        /// </summary>
        public static string readingMatrix {
            get {
                return ResourceManager.GetString("readingMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current game as....
        /// </summary>
        public static string romSaveTitle {
            get {
                return ResourceManager.GetString("romSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving ROM....
        /// </summary>
        public static string savingROM {
            get {
                return ResourceManager.GetString("savingROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script .
        /// </summary>
        public static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a model file to import.
        /// </summary>
        public static string selectModel {
            get {
                return ResourceManager.GetString("selectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid Pokémon Gen IV or Gen V ROM.
        /// </summary>
        public static string selectROM {
            get {
                return ResourceManager.GetString("selectROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: Pokémon SoulSilver .
        /// </summary>
        public static string soulsilver {
            get {
                return ResourceManager.GetString("soulsilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoulSilver.
        /// </summary>
        public static string soulsilverb {
            get {
                return ResourceManager.GetString("soulsilverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SPA).
        /// </summary>
        public static string spa {
            get {
                return ResourceManager.GetString("spa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NITRO Composer Sequence files (*.sseq)|*.sseq.
        /// </summary>
        public static string sseqFilter {
            get {
                return ResourceManager.GetString("sseqFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit? Unsaved ROM data will be lost permanently..
        /// </summary>
        public static string sureQuit {
            get {
                return ResourceManager.GetString("sureQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain files (*.bdhc)|*.bdhc.
        /// </summary>
        public static string terrainFile {
            get {
                return ResourceManager.GetString("terrainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text .
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset .
        /// </summary>
        public static string tileset {
            get {
                return ResourceManager.GetString("tileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not a valid tileset.
        /// </summary>
        public static string tilesetError {
            get {
                return ResourceManager.GetString("tilesetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo DS Texture Files (*.nsbtx)|*.nsbtx.
        /// </summary>
        public static string tilesetFile {
            get {
                return ResourceManager.GetString("tilesetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger .
        /// </summary>
        public static string trigger {
            get {
                return ResourceManager.GetString("trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ROM file.
        /// </summary>
        public static string unsupported {
            get {
                return ResourceManager.GetString("unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Textures.
        /// </summary>
        public static string untextured {
            get {
                return ResourceManager.GetString("untextured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (USA/ENG).
        /// </summary>
        public static string usa {
            get {
                return ResourceManager.GetString("usa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number between 0 and 255.
        /// </summary>
        public static string value255 {
            get {
                return ResourceManager.GetString("value255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number between 0 and 65535.
        /// </summary>
        public static string value65535 {
            get {
                return ResourceManager.GetString("value65535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be an hex number between 0 and FF.
        /// </summary>
        public static string valueFF {
            get {
                return ResourceManager.GetString("valueFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number between 0 and 4294967295.
        /// </summary>
        public static string valueFFFFFFFF {
            get {
                return ResourceManager.GetString("valueFFFFFFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp .
        /// </summary>
        public static string warp {
            get {
                return ResourceManager.GetString("warp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: Pokémon White .
        /// </summary>
        public static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game: Pokémon White 2 .
        /// </summary>
        public static string white2 {
            get {
                return ResourceManager.GetString("white2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White 2.
        /// </summary>
        public static string white2b {
            get {
                return ResourceManager.GetString("white2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string whiteb {
            get {
                return ResourceManager.GetString("whiteb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Pokémon .
        /// </summary>
        public static string wildPokemon {
            get {
                return ResourceManager.GetString("wildPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing headers....
        /// </summary>
        public static string writingHeaders {
            get {
                return ResourceManager.GetString("writingHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing map matrix....
        /// </summary>
        public static string writingMatrix {
            get {
                return ResourceManager.GetString("writingMatrix", resourceCulture);
            }
        }
    }
}
