//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptNamesW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptNamesW() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Resources.ScriptNamesW", typeof(ScriptNamesW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02AC.
        /// </summary>
        internal static string ActivateMysteryGift {
            get {
                return ResourceManager.GetString("ActivateMysteryGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0158.
        /// </summary>
        internal static string ActivatePokedex {
            get {
                return ResourceManager.GetString("ActivatePokedex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0133.
        /// </summary>
        internal static string ActivatePoketchApp {
            get {
                return ResourceManager.GetString("ActivatePoketchApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00EA.
        /// </summary>
        internal static string ActLeagueBattlers {
            get {
                return ResourceManager.GetString("ActLeagueBattlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0064.
        /// </summary>
        internal static string AddPeople {
            get {
                return ResourceManager.GetString("AddPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005E.
        /// </summary>
        internal static string ApplyMovement {
            get {
                return ResourceManager.GetString("ApplyMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02A1.
        /// </summary>
        internal static string ApplyMovement2 {
            get {
                return ResourceManager.GetString("ApplyMovement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01D9.
        /// </summary>
        internal static string BattleRoomResult {
            get {
                return ResourceManager.GetString("BattleRoomResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00CB.
        /// </summary>
        internal static string BerryHiroAnimation {
            get {
                return ResourceManager.GetString("BerryHiroAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01D7.
        /// </summary>
        internal static string BerryPoffin {
            get {
                return ResourceManager.GetString("BerryPoffin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02BF.
        /// </summary>
        internal static string BikeRide {
            get {
                return ResourceManager.GetString("BikeRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AB.
        /// </summary>
        internal static string BoxPokemon {
            get {
                return ResourceManager.GetString("BoxPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001A.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A1.
        /// </summary>
        internal static string CallEnd {
            get {
                return ResourceManager.GetString("CallEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0036.
        /// </summary>
        internal static string CallMessageBox {
            get {
                return ResourceManager.GetString("CallMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003A.
        /// </summary>
        internal static string CallMessageBoxText {
            get {
                return ResourceManager.GetString("CallMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0014.
        /// </summary>
        internal static string CallStandard {
            get {
                return ResourceManager.GetString("CallStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 029F.
        /// </summary>
        internal static string CameraBumpEffect {
            get {
                return ResourceManager.GetString("CameraBumpEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A9.
        /// </summary>
        internal static string CapsuleEditor {
            get {
                return ResourceManager.GetString("CapsuleEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0261.
        /// </summary>
        internal static string CheckAccessories {
            get {
                return ResourceManager.GetString("CheckAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015B.
        /// </summary>
        internal static string CheckBadge {
            get {
                return ResourceManager.GetString("CheckBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C7.
        /// </summary>
        internal static string CheckBike {
            get {
                return ResourceManager.GetString("CheckBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0252.
        /// </summary>
        internal static string CheckBoxesNumber {
            get {
                return ResourceManager.GetString("CheckBoxesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0078.
        /// </summary>
        internal static string CheckCoins {
            get {
                return ResourceManager.GetString("CheckCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 012E.
        /// </summary>
        internal static string CheckDress {
            get {
                return ResourceManager.GetString("CheckDress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 028F.
        /// </summary>
        internal static string CheckFirstTimeChampion {
            get {
                return ResourceManager.GetString("CheckFirstTimeChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0020.
        /// </summary>
        internal static string CheckFlag {
            get {
                return ResourceManager.GetString("CheckFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011C.
        /// </summary>
        internal static string CheckFloor {
            get {
                return ResourceManager.GetString("CheckFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01F1.
        /// </summary>
        internal static string CheckFossil {
            get {
                return ResourceManager.GetString("CheckFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014D.
        /// </summary>
        internal static string CheckGender {
            get {
                return ResourceManager.GetString("CheckGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01B9.
        /// </summary>
        internal static string CheckHappiness {
            get {
                return ResourceManager.GetString("CheckHappiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007D.
        /// </summary>
        internal static string CheckItem {
            get {
                return ResourceManager.GetString("CheckItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00EC.
        /// </summary>
        internal static string CheckLost {
            get {
                return ResourceManager.GetString("CheckLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024E.
        /// </summary>
        internal static string CheckLottoNumber {
            get {
                return ResourceManager.GetString("CheckLottoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0071.
        /// </summary>
        internal static string CheckMoney {
            get {
                return ResourceManager.GetString("CheckMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0099.
        /// </summary>
        internal static string CheckMove {
            get {
                return ResourceManager.GetString("CheckMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01E9.
        /// </summary>
        internal static string CheckNationalPokedex {
            get {
                return ResourceManager.GetString("CheckNationalPokedex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0177.
        /// </summary>
        internal static string CheckPartyNumber {
            get {
                return ResourceManager.GetString("CheckPartyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 019A.
        /// </summary>
        internal static string CheckPartyNumber2 {
            get {
                return ResourceManager.GetString("CheckPartyNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006B.
        /// </summary>
        internal static string CheckPersonPosition {
            get {
                return ResourceManager.GetString("CheckPersonPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0249.
        /// </summary>
        internal static string CheckPhraseBoxInput {
            get {
                return ResourceManager.GetString("CheckPhraseBoxInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 009A.
        /// </summary>
        internal static string CheckPlaceStored {
            get {
                return ResourceManager.GetString("CheckPlaceStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01C4.
        /// </summary>
        internal static string CheckPokemonHeight {
            get {
                return ResourceManager.GetString("CheckPokemonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01F6.
        /// </summary>
        internal static string CheckPokemonLevel {
            get {
                return ResourceManager.GetString("CheckPokemonLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0093.
        /// </summary>
        internal static string CheckPokemonParty {
            get {
                return ResourceManager.GetString("CheckPokemonParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01C0.
        /// </summary>
        internal static string CheckPokemonParty2 {
            get {
                return ResourceManager.GetString("CheckPokemonParty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0228.
        /// </summary>
        internal static string CheckPokemonTrade {
            get {
                return ResourceManager.GetString("CheckPokemonTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01BD.
        /// </summary>
        internal static string CheckPosition {
            get {
                return ResourceManager.GetString("CheckPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01E8.
        /// </summary>
        internal static string CheckSinnohPokedex {
            get {
                return ResourceManager.GetString("CheckSinnohPokedex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0069.
        /// </summary>
        internal static string CheckSpritePosition {
            get {
                return ResourceManager.GetString("CheckSpritePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007C.
        /// </summary>
        internal static string CheckStoreItem {
            get {
                return ResourceManager.GetString("CheckStoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0225.
        /// </summary>
        internal static string CheckTeachMove {
            get {
                return ResourceManager.GetString("CheckTeachMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0085.
        /// </summary>
        internal static string CheckUndergroundPcStatus {
            get {
                return ResourceManager.GetString("CheckUndergroundPcStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02C7.
        /// </summary>
        internal static string CheckVersionGame {
            get {
                return ResourceManager.GetString("CheckVersionGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02BC.
        /// </summary>
        internal static string CheckWildBattle2 {
            get {
                return ResourceManager.GetString("CheckWildBattle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 029D.
        /// </summary>
        internal static string ChoiceMulti {
            get {
                return ResourceManager.GetString("ChoiceMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00F2.
        /// </summary>
        internal static string ChooseFriend {
            get {
                return ResourceManager.GetString("ChooseFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00BA.
        /// </summary>
        internal static string ChoosePlayerName {
            get {
                return ResourceManager.GetString("ChoosePlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0191.
        /// </summary>
        internal static string ChoosePokemonMenu {
            get {
                return ResourceManager.GetString("ChoosePokemonMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0192.
        /// </summary>
        internal static string ChoosePokemonMenu2 {
            get {
                return ResourceManager.GetString("ChoosePokemonMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00BB.
        /// </summary>
        internal static string ChoosePokemonName {
            get {
                return ResourceManager.GetString("ChoosePokemonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00B4.
        /// </summary>
        internal static string ChooseStarter {
            get {
                return ResourceManager.GetString("ChooseStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02A5.
        /// </summary>
        internal static string ChooseTradePokemon {
            get {
                return ResourceManager.GetString("ChooseTradePokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001E.
        /// </summary>
        internal static string ClearFlag {
            get {
                return ResourceManager.GetString("ClearFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 016C.
        /// </summary>
        internal static string CloseDoor {
            get {
                return ResourceManager.GetString("CloseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0034.
        /// </summary>
        internal static string CloseMessageOnKeyPress {
            get {
                return ResourceManager.GetString("CloseMessageOnKeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0043.
        /// </summary>
        internal static string CloseMulti {
            get {
                return ResourceManager.GetString("CloseMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024D.
        /// </summary>
        internal static string ClosePcAnimation {
            get {
                return ResourceManager.GetString("ClosePcAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0037.
        /// </summary>
        internal static string ColorMessageBox {
            get {
                return ResourceManager.GetString("ColorMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001D.
        /// </summary>
        internal static string CompareLastResultCall {
            get {
                return ResourceManager.GetString("CompareLastResultCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001C.
        /// </summary>
        internal static string CompareLastResultJump {
            get {
                return ResourceManager.GetString("CompareLastResultJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024F.
        /// </summary>
        internal static string CompareLottoNumber {
            get {
                return ResourceManager.GetString("CompareLottoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02AA.
        /// </summary>
        internal static string ComparePhraseBoxInput {
            get {
                return ResourceManager.GetString("ComparePhraseBoxInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01C3.
        /// </summary>
        internal static string ComparePokemonHeight {
            get {
                return ResourceManager.GetString("ComparePokemonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0026.
        /// </summary>
        internal static string CompareVarsToByte {
            get {
                return ResourceManager.GetString("CompareVarsToByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006C.
        /// </summary>
        internal static string ContinueFollow {
            get {
                return ResourceManager.GetString("ContinueFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01C1.
        /// </summary>
        internal static string CopyPokemonHeight {
            get {
                return ResourceManager.GetString("CopyPokemonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0029.
        /// </summary>
        internal static string CopyVar {
            get {
                return ResourceManager.GetString("CopyVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0239.
        /// </summary>
        internal static string DecideRules {
            get {
                return ResourceManager.GetString("DecideRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014B.
        /// </summary>
        internal static string DefeatGoPokecenter {
            get {
                return ResourceManager.GetString("DefeatGoPokecenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01C9.
        /// </summary>
        internal static string DeleteMove {
            get {
                return ResourceManager.GetString("DeleteMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015D.
        /// </summary>
        internal static string DisableBadge {
            get {
                return ResourceManager.GetString("DisableBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A8.
        /// </summary>
        internal static string DisplayContestPokemon {
            get {
                return ResourceManager.GetString("DisplayContestPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A7.
        /// </summary>
        internal static string DisplayDressedPokemon {
            get {
                return ResourceManager.GetString("DisplayDressedPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0347.
        /// </summary>
        internal static string DisplayFloor {
            get {
                return ResourceManager.GetString("DisplayFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02A0.
        /// </summary>
        internal static string DoubleBattle {
            get {
                return ResourceManager.GetString("DoubleBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AC.
        /// </summary>
        internal static string DrawUnion {
            get {
                return ResourceManager.GetString("DrawUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A6.
        /// </summary>
        internal static string DressPokemon {
            get {
                return ResourceManager.GetString("DressPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01AC.
        /// </summary>
        internal static string EggAnimation {
            get {
                return ResourceManager.GetString("EggAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0259.
        /// </summary>
        internal static string ElevLgAnimation {
            get {
                return ResourceManager.GetString("ElevLgAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015C.
        /// </summary>
        internal static string EnableBadge {
            get {
                return ResourceManager.GetString("EnableBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0002.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0112.
        /// </summary>
        internal static string EndFlash {
            get {
                return ResourceManager.GetString("EndFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00B0.
        /// </summary>
        internal static string EndGame {
            get {
                return ResourceManager.GetString("EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00E6.
        /// </summary>
        internal static string EndTrainerBattle {
            get {
                return ResourceManager.GetString("EndTrainerBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0143.
        /// </summary>
        internal static string ExpectDecisionOther {
            get {
                return ResourceManager.GetString("ExpectDecisionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0126.
        /// </summary>
        internal static string ExplanationBattle {
            get {
                return ResourceManager.GetString("ExplanationBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0068.
        /// </summary>
        internal static string FacePlayer {
            get {
                return ResourceManager.GetString("FacePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004F.
        /// </summary>
        internal static string FadeDefaultMusic {
            get {
                return ResourceManager.GetString("FadeDefaultMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00BC.
        /// </summary>
        internal static string FadeScreen {
            get {
                return ResourceManager.GetString("FadeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0111.
        /// </summary>
        internal static string FlashContest {
            get {
                return ResourceManager.GetString("FlashContest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02CA.
        /// </summary>
        internal static string FloralClockAnimation {
            get {
                return ResourceManager.GetString("FloralClockAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C2.
        /// </summary>
        internal static string FlyAnimation {
            get {
                return ResourceManager.GetString("FlyAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006D.
        /// </summary>
        internal static string FollowHero {
            get {
                return ResourceManager.GetString("FollowHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0035.
        /// </summary>
        internal static string FreezeMessageBox {
            get {
                return ResourceManager.GetString("FreezeMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0205.
        /// </summary>
        internal static string Geonet {
            get {
                return ResourceManager.GetString("Geonet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0079.
        /// </summary>
        internal static string GiveCoins {
            get {
                return ResourceManager.GetString("GiveCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0097.
        /// </summary>
        internal static string GiveEgg {
            get {
                return ResourceManager.GetString("GiveEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006F.
        /// </summary>
        internal static string GiveMoney {
            get {
                return ResourceManager.GetString("GiveMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0096.
        /// </summary>
        internal static string GivePokemon {
            get {
                return ResourceManager.GetString("GivePokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0131.
        /// </summary>
        internal static string GivePoketch {
            get {
                return ResourceManager.GetString("GivePoketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015A.
        /// </summary>
        internal static string GiveRunningShoes {
            get {
                return ResourceManager.GetString("GiveRunningShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0206.
        /// </summary>
        internal static string GreatMarshBynocule {
            get {
                return ResourceManager.GetString("GreatMarshBynocule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00B1.
        /// </summary>
        internal static string HallFameData {
            get {
                return ResourceManager.GetString("HallFameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014E.
        /// </summary>
        internal static string HealPokemon {
            get {
                return ResourceManager.GetString("HealPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 023B.
        /// </summary>
        internal static string HealPokemonAnimation {
            get {
                return ResourceManager.GetString("HealPokemonAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 029E.
        /// </summary>
        internal static string HiddenMachineEffect {
            get {
                return ResourceManager.GetString("HiddenMachineEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0295.
        /// </summary>
        internal static string HideBattlePointsBox {
            get {
                return ResourceManager.GetString("HideBattlePointsBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0076.
        /// </summary>
        internal static string HideCoins {
            get {
                return ResourceManager.GetString("HideCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0073.
        /// </summary>
        internal static string HideMoney {
            get {
                return ResourceManager.GetString("HideMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0209.
        /// </summary>
        internal static string HidePicture {
            get {
                return ResourceManager.GetString("HidePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02C2.
        /// </summary>
        internal static string HideSaveBox {
            get {
                return ResourceManager.GetString("HideSaveBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018E.
        /// </summary>
        internal static string HideSavingClock {
            get {
                return ResourceManager.GetString("HideSavingClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0127.
        /// </summary>
        internal static string HoneyTreeBattle {
            get {
                return ResourceManager.GetString("HoneyTreeBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0011.
        /// </summary>
        internal static string If {
            get {
                return ResourceManager.GetString("If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0012.
        /// </summary>
        internal static string If2 {
            get {
                return ResourceManager.GetString("If2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A5.
        /// </summary>
        internal static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0016.
        /// </summary>
        internal static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 027A.
        /// </summary>
        internal static string LeagueCastleView {
            get {
                return ResourceManager.GetString("LeagueCastleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0062.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0060.
        /// </summary>
        internal static string LockAll {
            get {
                return ResourceManager.GetString("LockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0066.
        /// </summary>
        internal static string LockCam {
            get {
                return ResourceManager.GetString("LockCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00EB.
        /// </summary>
        internal static string LostGoPokecenter {
            get {
                return ResourceManager.GetString("LostGoPokecenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01B3.
        /// </summary>
        internal static string Mailbox {
            get {
                return ResourceManager.GetString("Mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003C.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002C.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002D.
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002F.
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01C6.
        /// </summary>
        internal static string MoveInfo {
            get {
                return ResourceManager.GetString("MoveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0040.
        /// </summary>
        internal static string Multi {
            get {
                return ResourceManager.GetString("Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0041.
        /// </summary>
        internal static string Multi2 {
            get {
                return ResourceManager.GetString("Multi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0044.
        /// </summary>
        internal static string Multi3 {
            get {
                return ResourceManager.GetString("Multi3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0048.
        /// </summary>
        internal static string MultiRow {
            get {
                return ResourceManager.GetString("MultiRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0039.
        /// </summary>
        internal static string NoMapMessageBox {
            get {
                return ResourceManager.GetString("NoMapMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        internal static string Nop {
            get {
                return ResourceManager.GetString("Nop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001.
        /// </summary>
        internal static string Nop1 {
            get {
                return ResourceManager.GetString("Nop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0178.
        /// </summary>
        internal static string OpenBerryPouch {
            get {
                return ResourceManager.GetString("OpenBerryPouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 016B.
        /// </summary>
        internal static string OpenDoor {
            get {
                return ResourceManager.GetString("OpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024C.
        /// </summary>
        internal static string OpenPcAnimation {
            get {
                return ResourceManager.GetString("OpenPcAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0243.
        /// </summary>
        internal static string PhraseBox1W {
            get {
                return ResourceManager.GetString("PhraseBox1W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0244.
        /// </summary>
        internal static string PhraseBox2W {
            get {
                return ResourceManager.GetString("PhraseBox2W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004C.
        /// </summary>
        internal static string PlayCry {
            get {
                return ResourceManager.GetString("PlayCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0049.
        /// </summary>
        internal static string PlayFanfare {
            get {
                return ResourceManager.GetString("PlayFanfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004A.
        /// </summary>
        internal static string PlayFanfare2 {
            get {
                return ResourceManager.GetString("PlayFanfare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0050.
        /// </summary>
        internal static string PlayMusic {
            get {
                return ResourceManager.GetString("PlayMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004E.
        /// </summary>
        internal static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0267.
        /// </summary>
        internal static string Pokecasino {
            get {
                return ResourceManager.GetString("Pokecasino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0147.
        /// </summary>
        internal static string Pokemart {
            get {
                return ResourceManager.GetString("Pokemart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0148.
        /// </summary>
        internal static string Pokemart1 {
            get {
                return ResourceManager.GetString("Pokemart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0149.
        /// </summary>
        internal static string Pokemart2 {
            get {
                return ResourceManager.GetString("Pokemart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014A.
        /// </summary>
        internal static string Pokemart3 {
            get {
                return ResourceManager.GetString("Pokemart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00F7.
        /// </summary>
        internal static string PokemonContest {
            get {
                return ResourceManager.GetString("PokemonContest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0195.
        /// </summary>
        internal static string PokemonInfo {
            get {
                return ResourceManager.GetString("PokemonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 028C.
        /// </summary>
        internal static string PokemonPartyPicture {
            get {
                return ResourceManager.GetString("PokemonPartyPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0208.
        /// </summary>
        internal static string PokemonPicture {
            get {
                return ResourceManager.GetString("PokemonPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0328.
        /// </summary>
        internal static string PortalEffect {
            get {
                return ResourceManager.GetString("PortalEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0168.
        /// </summary>
        internal static string PrepareDoorAnimation {
            get {
                return ResourceManager.GetString("PrepareDoorAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024B.
        /// </summary>
        internal static string PreparePcAnimation {
            get {
                return ResourceManager.GetString("PreparePcAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0129.
        /// </summary>
        internal static string RandomBattle {
            get {
                return ResourceManager.GetString("RandomBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01B5.
        /// </summary>
        internal static string RecordList {
            get {
                return ResourceManager.GetString("RecordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AF.
        /// </summary>
        internal static string RecordMixingUnion {
            get {
                return ResourceManager.GetString("RecordMixingUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0063.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0061.
        /// </summary>
        internal static string ReleaseAll {
            get {
                return ResourceManager.GetString("ReleaseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0189.
        /// </summary>
        internal static string ReleaseOverworld {
            get {
                return ResourceManager.GetString("ReleaseOverworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0221.
        /// </summary>
        internal static string RememberMove {
            get {
                return ResourceManager.GetString("RememberMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0065.
        /// </summary>
        internal static string RemovePeople {
            get {
                return ResourceManager.GetString("RemovePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00BD.
        /// </summary>
        internal static string ResetScreen {
            get {
                return ResourceManager.GetString("ResetScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0052.
        /// </summary>
        internal static string RestartMusic {
            get {
                return ResourceManager.GetString("RestartMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0258.
        /// </summary>
        internal static string RetSprtSave {
            get {
                return ResourceManager.GetString("RetSprtSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001B.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0003.
        /// </summary>
        internal static string Return2 {
            get {
                return ResourceManager.GetString("Return2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C8.
        /// </summary>
        internal static string RideBike {
            get {
                return ResourceManager.GetString("RideBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00BF.
        /// </summary>
        internal static string RockClimbAnimation {
            get {
                return ResourceManager.GetString("RockClimbAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018B.
        /// </summary>
        internal static string SetDoorLocked {
            get {
                return ResourceManager.GetString("SetDoorLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018A.
        /// </summary>
        internal static string SetDoorPassable {
            get {
                return ResourceManager.GetString("SetDoorPassable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001F.
        /// </summary>
        internal static string SetFlag {
            get {
                return ResourceManager.GetString("SetFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0188.
        /// </summary>
        internal static string SetOverworldMovement {
            get {
                return ResourceManager.GetString("SetOverworldMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0186.
        /// </summary>
        internal static string SetOverworldPosition {
            get {
                return ResourceManager.GetString("SetOverworldPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0095.
        /// </summary>
        internal static string SetPokemonPartyStored {
            get {
                return ResourceManager.GetString("SetPokemonPartyStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0120.
        /// </summary>
        internal static string SetPositionAfterShip {
            get {
                return ResourceManager.GetString("SetPositionAfterShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0023.
        /// </summary>
        internal static string SetValue {
            get {
                return ResourceManager.GetString("SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0028.
        /// </summary>
        internal static string SetVar {
            get {
                return ResourceManager.GetString("SetVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00DD.
        /// </summary>
        internal static string SetVarAlterStored {
            get {
                return ResourceManager.GetString("SetVarAlterStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00DB.
        /// </summary>
        internal static string SetVarHeroStored {
            get {
                return ResourceManager.GetString("SetVarHeroStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00CF.
        /// </summary>
        internal static string SetVariableAlter {
            get {
                return ResourceManager.GetString("SetVariableAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00D4.
        /// </summary>
        internal static string SetVariableAttack {
            get {
                return ResourceManager.GetString("SetVariableAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00D3.
        /// </summary>
        internal static string SetVariableAttackItem {
            get {
                return ResourceManager.GetString("SetVariableAttackItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00CD.
        /// </summary>
        internal static string SetVariableHero {
            get {
                return ResourceManager.GetString("SetVariableHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00D1.
        /// </summary>
        internal static string SetVariableItem {
            get {
                return ResourceManager.GetString("SetVariableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00D6.
        /// </summary>
        internal static string SetVariableNickname {
            get {
                return ResourceManager.GetString("SetVariableNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00D5.
        /// </summary>
        internal static string SetVariableNumber {
            get {
                return ResourceManager.GetString("SetVariableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00D7.
        /// </summary>
        internal static string SetVariableObject {
            get {
                return ResourceManager.GetString("SetVariableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00D0.
        /// </summary>
        internal static string SetVariablePokemon {
            get {
                return ResourceManager.GetString("SetVariablePokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01C2.
        /// </summary>
        internal static string SetVariablePokemonHeight {
            get {
                return ResourceManager.GetString("SetVariablePokemonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00CE.
        /// </summary>
        internal static string SetVariableRival {
            get {
                return ResourceManager.GetString("SetVariableRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00D8.
        /// </summary>
        internal static string SetVariableTrainer {
            get {
                return ResourceManager.GetString("SetVariableTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00DA.
        /// </summary>
        internal static string SetVarPokemonStored {
            get {
                return ResourceManager.GetString("SetVarPokemonStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00DC.
        /// </summary>
        internal static string SetVarRivalStored {
            get {
                return ResourceManager.GetString("SetVarRivalStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 023D.
        /// </summary>
        internal static string ShipAnimation {
            get {
                return ResourceManager.GetString("ShipAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0294.
        /// </summary>
        internal static string ShowBattlePointsBox {
            get {
                return ResourceManager.GetString("ShowBattlePointsBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0075.
        /// </summary>
        internal static string ShowCoins {
            get {
                return ResourceManager.GetString("ShowCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0116.
        /// </summary>
        internal static string ShowLinkCountRecord {
            get {
                return ResourceManager.GetString("ShowLinkCountRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0072.
        /// </summary>
        internal static string ShowMoney {
            get {
                return ResourceManager.GetString("ShowMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01EB.
        /// </summary>
        internal static string ShowNationalSheet {
            get {
                return ResourceManager.GetString("ShowNationalSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02C1.
        /// </summary>
        internal static string ShowSaveBox {
            get {
                return ResourceManager.GetString("ShowSaveBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018D.
        /// </summary>
        internal static string ShowSavingClock {
            get {
                return ResourceManager.GetString("ShowSavingClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01EA.
        /// </summary>
        internal static string ShowSinnohSheet {
            get {
                return ResourceManager.GetString("ShowSinnohSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AA.
        /// </summary>
        internal static string SinnohMaps {
            get {
                return ResourceManager.GetString("SinnohMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02C6.
        /// </summary>
        internal static string SpinTradeUnion {
            get {
                return ResourceManager.GetString("SpinTradeUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0257.
        /// </summary>
        internal static string SprtSave {
            get {
                return ResourceManager.GetString("SprtSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0125.
        /// </summary>
        internal static string StarterBattle {
            get {
                return ResourceManager.GetString("StarterBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00CC.
        /// </summary>
        internal static string StopBerryHiroAnimation {
            get {
                return ResourceManager.GetString("StopBerryHiroAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006E.
        /// </summary>
        internal static string StopFollowHero {
            get {
                return ResourceManager.GetString("StopFollowHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0051.
        /// </summary>
        internal static string StopMusic {
            get {
                return ResourceManager.GetString("StopMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 022A.
        /// </summary>
        internal static string StopTrade {
            get {
                return ResourceManager.GetString("StopTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01C7.
        /// </summary>
        internal static string StoreMove {
            get {
                return ResourceManager.GetString("StoreMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0193.
        /// </summary>
        internal static string StorePokemonMenu2 {
            get {
                return ResourceManager.GetString("StorePokemonMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0198.
        /// </summary>
        internal static string StorePokemonNumber {
            get {
                return ResourceManager.GetString("StorePokemonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0094.
        /// </summary>
        internal static string StorePokemonParty {
            get {
                return ResourceManager.GetString("StorePokemonParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0134.
        /// </summary>
        internal static string StorePoketchApp {
            get {
                return ResourceManager.GetString("StorePoketchApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00DE.
        /// </summary>
        internal static string StoreStarter {
            get {
                return ResourceManager.GetString("StoreStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C0.
        /// </summary>
        internal static string SurfAnimation {
            get {
                return ResourceManager.GetString("SurfAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0054.
        /// </summary>
        internal static string SwitchMusic {
            get {
                return ResourceManager.GetString("SwitchMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005A.
        /// </summary>
        internal static string SwitchMusic2 {
            get {
                return ResourceManager.GetString("SwitchMusic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007A.
        /// </summary>
        internal static string TakeCoins {
            get {
                return ResourceManager.GetString("TakeCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007B.
        /// </summary>
        internal static string TakeItem {
            get {
                return ResourceManager.GetString("TakeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0070.
        /// </summary>
        internal static string TakeMoney {
            get {
                return ResourceManager.GetString("TakeMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0224.
        /// </summary>
        internal static string TeachMove {
            get {
                return ResourceManager.GetString("TeachMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0046.
        /// </summary>
        internal static string TextMessageScriptMulti {
            get {
                return ResourceManager.GetString("TextMessageScriptMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0042.
        /// </summary>
        internal static string TextScriptMulti {
            get {
                return ResourceManager.GetString("TextScriptMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0271.
        /// </summary>
        internal static string ThankNameInsert {
            get {
                return ResourceManager.GetString("ThankNameInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0229.
        /// </summary>
        internal static string TradeChosenPokemon {
            get {
                return ResourceManager.GetString("TradeChosenPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AE.
        /// </summary>
        internal static string TradeUnion {
            get {
                return ResourceManager.GetString("TradeUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00E5.
        /// </summary>
        internal static string TrainerBattle {
            get {
                return ResourceManager.GetString("TrainerBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AD.
        /// </summary>
        internal static string TrainerCaseUnion {
            get {
                return ResourceManager.GetString("TrainerCaseUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C6.
        /// </summary>
        internal static string Tuxedo {
            get {
                return ResourceManager.GetString("Tuxedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0038.
        /// </summary>
        internal static string TypeMessageBox {
            get {
                return ResourceManager.GetString("TypeMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0153.
        /// </summary>
        internal static string UnionRoom {
            get {
                return ResourceManager.GetString("UnionRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 026D.
        /// </summary>
        internal static string UnownMessageBox {
            get {
                return ResourceManager.GetString("UnownMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0077.
        /// </summary>
        internal static string UpdateCoins {
            get {
                return ResourceManager.GetString("UpdateCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0074.
        /// </summary>
        internal static string UpdateMoney {
            get {
                return ResourceManager.GetString("UpdateMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0169.
        /// </summary>
        internal static string WaitAction {
            get {
                return ResourceManager.GetString("WaitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0031.
        /// </summary>
        internal static string WaitButton {
            get {
                return ResourceManager.GetString("WaitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 016A.
        /// </summary>
        internal static string WaitClose {
            get {
                return ResourceManager.GetString("WaitClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004D.
        /// </summary>
        internal static string WaitCry {
            get {
                return ResourceManager.GetString("WaitCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004B.
        /// </summary>
        internal static string WaitFanfare {
            get {
                return ResourceManager.GetString("WaitFanfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003F.
        /// </summary>
        internal static string WaitFor {
            get {
                return ResourceManager.GetString("WaitFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005F.
        /// </summary>
        internal static string WaitMovement {
            get {
                return ResourceManager.GetString("WaitMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00BE.
        /// </summary>
        internal static string Warp {
            get {
                return ResourceManager.GetString("Warp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0204.
        /// </summary>
        internal static string WarpLastElevator {
            get {
                return ResourceManager.GetString("WarpLastElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011B.
        /// </summary>
        internal static string WarpMapElevator {
            get {
                return ResourceManager.GetString("WarpMapElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C1.
        /// </summary>
        internal static string WaterfallAnimation {
            get {
                return ResourceManager.GetString("WaterfallAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A3.
        /// </summary>
        internal static string WFC {
            get {
                return ResourceManager.GetString("WFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00B3.
        /// </summary>
        internal static string WFC1 {
            get {
                return ResourceManager.GetString("WFC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0124.
        /// </summary>
        internal static string WildBattle {
            get {
                return ResourceManager.GetString("WildBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02BD.
        /// </summary>
        internal static string WildBattle2 {
            get {
                return ResourceManager.GetString("WildBattle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00F3.
        /// </summary>
        internal static string WirelessBattleWait {
            get {
                return ResourceManager.GetString("WirelessBattleWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 012B.
        /// </summary>
        internal static string WriteAutograph {
            get {
                return ResourceManager.GetString("WriteAutograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003E.
        /// </summary>
        internal static string YesNoBox {
            get {
                return ResourceManager.GetString("YesNoBox", resourceCulture);
            }
        }
    }
}
