//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptNamesWGS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptNamesWGS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Resources.ScriptNamesWGS", typeof(ScriptNamesWGS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123.
        /// </summary>
        internal static string ActivatePokedex {
            get {
                return ResourceManager.GetString("ActivatePokedex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0064.
        /// </summary>
        internal static string AddPeople {
            get {
                return ResourceManager.GetString("AddPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005E.
        /// </summary>
        internal static string ApplyMovement {
            get {
                return ResourceManager.GetString("ApplyMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0147.
        /// </summary>
        internal static string AzaleaGym {
            get {
                return ResourceManager.GetString("AzaleaGym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0148.
        /// </summary>
        internal static string AzaleaGym2 {
            get {
                return ResourceManager.GetString("AzaleaGym2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001A.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0096.
        /// </summary>
        internal static string CallEnd {
            get {
                return ResourceManager.GetString("CallEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A1.
        /// </summary>
        internal static string CallEnd2 {
            get {
                return ResourceManager.GetString("CallEnd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0037.
        /// </summary>
        internal static string CallMessageBox {
            get {
                return ResourceManager.GetString("CallMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0014.
        /// </summary>
        internal static string CallStandard {
            get {
                return ResourceManager.GetString("CallStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 026A.
        /// </summary>
        internal static string CheckAlbumPhoto {
            get {
                return ResourceManager.GetString("CheckAlbumPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0126.
        /// </summary>
        internal static string CheckBadge {
            get {
                return ResourceManager.GetString("CheckBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01FB.
        /// </summary>
        internal static string CheckBoxesNumber {
            get {
                return ResourceManager.GetString("CheckBoxesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0020.
        /// </summary>
        internal static string CheckFlag {
            get {
                return ResourceManager.GetString("CheckFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00F1.
        /// </summary>
        internal static string CheckFloor {
            get {
                return ResourceManager.GetString("CheckFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0119.
        /// </summary>
        internal static string CheckGender {
            get {
                return ResourceManager.GetString("CheckGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0170.
        /// </summary>
        internal static string CheckHiroMoneyNumber {
            get {
                return ResourceManager.GetString("CheckHiroMoneyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0163.
        /// </summary>
        internal static string CheckIfPokemonTraded {
            get {
                return ResourceManager.GetString("CheckIfPokemonTraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0080.
        /// </summary>
        internal static string CheckItem {
            get {
                return ResourceManager.GetString("CheckItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00DC.
        /// </summary>
        internal static string CheckLost {
            get {
                return ResourceManager.GetString("CheckLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0179.
        /// </summary>
        internal static string CheckMail {
            get {
                return ResourceManager.GetString("CheckMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0346.
        /// </summary>
        internal static string CheckMomMoneyNumber {
            get {
                return ResourceManager.GetString("CheckMomMoneyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0070.
        /// </summary>
        internal static string CheckMoney {
            get {
                return ResourceManager.GetString("CheckMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018C.
        /// </summary>
        internal static string CheckMoveNumber {
            get {
                return ResourceManager.GetString("CheckMoveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014C.
        /// </summary>
        internal static string CheckPartyNumber {
            get {
                return ResourceManager.GetString("CheckPartyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006B.
        /// </summary>
        internal static string CheckPersonPosition {
            get {
                return ResourceManager.GetString("CheckPersonPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0189.
        /// </summary>
        internal static string CheckPokemonHeight {
            get {
                return ResourceManager.GetString("CheckPokemonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01E3.
        /// </summary>
        internal static string CheckPokemonRibbon {
            get {
                return ResourceManager.GetString("CheckPokemonRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01D8.
        /// </summary>
        internal static string CheckPokemonTrade {
            get {
                return ResourceManager.GetString("CheckPokemonTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01E0.
        /// </summary>
        internal static string CheckRibbon {
            get {
                return ResourceManager.GetString("CheckRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0069.
        /// </summary>
        internal static string CheckSpritePosition {
            get {
                return ResourceManager.GetString("CheckSpritePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00CD.
        /// </summary>
        internal static string CheckStarter {
            get {
                return ResourceManager.GetString("CheckStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01EF.
        /// </summary>
        internal static string CheckVersion {
            get {
                return ResourceManager.GetString("CheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02BC.
        /// </summary>
        internal static string CheckWildBattle2 {
            get {
                return ResourceManager.GetString("CheckWildBattle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00EF.
        /// </summary>
        internal static string ChecPokemonGender {
            get {
                return ResourceManager.GetString("ChecPokemonGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018A.
        /// </summary>
        internal static string ChoosePokemonDelete {
            get {
                return ResourceManager.GetString("ChoosePokemonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015D.
        /// </summary>
        internal static string ChoosePokemonMenu {
            get {
                return ResourceManager.GetString("ChoosePokemonMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015E.
        /// </summary>
        internal static string ChoosePokemonMenu2 {
            get {
                return ResourceManager.GetString("ChoosePokemonMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0236.
        /// </summary>
        internal static string ChoosePokemonMenuTrade {
            get {
                return ResourceManager.GetString("ChoosePokemonMenuTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01D3.
        /// </summary>
        internal static string ChoosePokemonRem {
            get {
                return ResourceManager.GetString("ChoosePokemonRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001F.
        /// </summary>
        internal static string ClearFlag {
            get {
                return ResourceManager.GetString("ClearFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0134.
        /// </summary>
        internal static string CloseDoor {
            get {
                return ResourceManager.GetString("CloseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02EB.
        /// </summary>
        internal static string CloseLowScreen {
            get {
                return ResourceManager.GetString("CloseLowScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0035.
        /// </summary>
        internal static string CloseMessageOnKeyPress {
            get {
                return ResourceManager.GetString("CloseMessageOnKeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 031C.
        /// </summary>
        internal static string CloseMomMoneyBox {
            get {
                return ResourceManager.GetString("CloseMomMoneyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0043.
        /// </summary>
        internal static string CloseMulti {
            get {
                return ResourceManager.GetString("CloseMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02F0.
        /// </summary>
        internal static string CloseMulti4 {
            get {
                return ResourceManager.GetString("CloseMulti4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0038.
        /// </summary>
        internal static string ColorMessageBox {
            get {
                return ResourceManager.GetString("ColorMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001D.
        /// </summary>
        internal static string CompareLastResultCall {
            get {
                return ResourceManager.GetString("CompareLastResultCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001C.
        /// </summary>
        internal static string CompareLastResultJump {
            get {
                return ResourceManager.GetString("CompareLastResultJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0188.
        /// </summary>
        internal static string ComparePokemonHeight {
            get {
                return ResourceManager.GetString("ComparePokemonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006C.
        /// </summary>
        internal static string ContinueFollow {
            get {
                return ResourceManager.GetString("ContinueFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0027.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002A.
        /// </summary>
        internal static string CopyVar {
            get {
                return ResourceManager.GetString("CopyVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018D.
        /// </summary>
        internal static string DeleteMove {
            get {
                return ResourceManager.GetString("DeleteMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0128.
        /// </summary>
        internal static string DisableBadge {
            get {
                return ResourceManager.GetString("DisableBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0084.
        /// </summary>
        internal static string DoubleMessage {
            get {
                return ResourceManager.GetString("DoubleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0127.
        /// </summary>
        internal static string EnableBadge {
            get {
                return ResourceManager.GetString("EnableBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0002.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 025E.
        /// </summary>
        internal static string EndFriendPark {
            get {
                return ResourceManager.GetString("EndFriendPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A3.
        /// </summary>
        internal static string EndGame {
            get {
                return ResourceManager.GetString("EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0068.
        /// </summary>
        internal static string FacePlayer {
            get {
                return ResourceManager.GetString("FacePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004F.
        /// </summary>
        internal static string FadeDefaultMusic {
            get {
                return ResourceManager.GetString("FadeDefaultMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AE.
        /// </summary>
        internal static string FadeScreen {
            get {
                return ResourceManager.GetString("FadeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006D.
        /// </summary>
        internal static string FollowHero {
            get {
                return ResourceManager.GetString("FollowHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0036.
        /// </summary>
        internal static string FreezeMessageBox {
            get {
                return ResourceManager.GetString("FreezeMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007F.
        /// </summary>
        internal static string GiveItem {
            get {
                return ResourceManager.GetString("GiveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0194.
        /// </summary>
        internal static string GiveItemStored {
            get {
                return ResourceManager.GetString("GiveItemStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 031A.
        /// </summary>
        internal static string GiveMomMoney {
            get {
                return ResourceManager.GetString("GiveMomMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006E.
        /// </summary>
        internal static string GiveMoney {
            get {
                return ResourceManager.GetString("GiveMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AD.
        /// </summary>
        internal static string GivePokemonNickname {
            get {
                return ResourceManager.GetString("GivePokemonNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01E1.
        /// </summary>
        internal static string GiveRibbon {
            get {
                return ResourceManager.GetString("GiveRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0125.
        /// </summary>
        internal static string GiveRunningShoes {
            get {
                return ResourceManager.GetString("GiveRunningShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0089.
        /// </summary>
        internal static string GiveStoredPokemon {
            get {
                return ResourceManager.GetString("GiveStoredPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00B1.
        /// </summary>
        internal static string HallFameData {
            get {
                return ResourceManager.GetString("HallFameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011A.
        /// </summary>
        internal static string HealPokemon {
            get {
                return ResourceManager.GetString("HealPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0072.
        /// </summary>
        internal static string HideMoney {
            get {
                return ResourceManager.GetString("HideMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0011.
        /// </summary>
        internal static string If {
            get {
                return ResourceManager.GetString("If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0012.
        /// </summary>
        internal static string If2 {
            get {
                return ResourceManager.GetString("If2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0016.
        /// </summary>
        internal static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024D.
        /// </summary>
        internal static string LegendaryBattle {
            get {
                return ResourceManager.GetString("LegendaryBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0062.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0060.
        /// </summary>
        internal static string LockAll {
            get {
                return ResourceManager.GetString("LockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0066.
        /// </summary>
        internal static string LockCam {
            get {
                return ResourceManager.GetString("LockCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00DB.
        /// </summary>
        internal static string LostGoPokecenter {
            get {
                return ResourceManager.GetString("LostGoPokecenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0267.
        /// </summary>
        internal static string MakePhoto {
            get {
                return ResourceManager.GetString("MakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0261.
        /// </summary>
        internal static string MecScript {
            get {
                return ResourceManager.GetString("MecScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002D.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002E.
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0135.
        /// </summary>
        internal static string MoveDoor {
            get {
                return ResourceManager.GetString("MoveDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0040.
        /// </summary>
        internal static string Multi {
            get {
                return ResourceManager.GetString("Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0041.
        /// </summary>
        internal static string Multi2 {
            get {
                return ResourceManager.GetString("Multi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0044.
        /// </summary>
        internal static string Multi3 {
            get {
                return ResourceManager.GetString("Multi3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02ED.
        /// </summary>
        internal static string Multi4 {
            get {
                return ResourceManager.GetString("Multi4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02EE.
        /// </summary>
        internal static string Multi5 {
            get {
                return ResourceManager.GetString("Multi5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0048.
        /// </summary>
        internal static string MultiRow {
            get {
                return ResourceManager.GetString("MultiRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003A.
        /// </summary>
        internal static string NoMapMessageBox {
            get {
                return ResourceManager.GetString("NoMapMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        internal static string Nop {
            get {
                return ResourceManager.GetString("Nop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001.
        /// </summary>
        internal static string Nop1 {
            get {
                return ResourceManager.GetString("Nop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0136.
        /// </summary>
        internal static string OpenDoor {
            get {
                return ResourceManager.GetString("OpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02EA.
        /// </summary>
        internal static string OpenLowScreen {
            get {
                return ResourceManager.GetString("OpenLowScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02EC.
        /// </summary>
        internal static string OpenLowYesNoBox {
            get {
                return ResourceManager.GetString("OpenLowYesNoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0178.
        /// </summary>
        internal static string OpenMail {
            get {
                return ResourceManager.GetString("OpenMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 031B.
        /// </summary>
        internal static string OpenMomMoneyBox {
            get {
                return ResourceManager.GetString("OpenMomMoneyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 009D.
        /// </summary>
        internal static string OpenPokegearMap {
            get {
                return ResourceManager.GetString("OpenPokegearMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 009A.
        /// </summary>
        internal static string OpenPokemonDress {
            get {
                return ResourceManager.GetString("OpenPokemonDress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004C.
        /// </summary>
        internal static string PlayCry {
            get {
                return ResourceManager.GetString("PlayCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0049.
        /// </summary>
        internal static string PlayFanfare {
            get {
                return ResourceManager.GetString("PlayFanfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004A.
        /// </summary>
        internal static string PlayFanfare2 {
            get {
                return ResourceManager.GetString("PlayFanfare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0050.
        /// </summary>
        internal static string PlayMusic {
            get {
                return ResourceManager.GetString("PlayMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004E.
        /// </summary>
        internal static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00F7.
        /// </summary>
        internal static string PokemonContest {
            get {
                return ResourceManager.GetString("PokemonContest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0133.
        /// </summary>
        internal static string PrepareDoorAnimation {
            get {
                return ResourceManager.GetString("PrepareDoorAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01E6.
        /// </summary>
        internal static string RBattleRecorder {
            get {
                return ResourceManager.GetString("RBattleRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0092.
        /// </summary>
        internal static string RecordPokegearNumber {
            get {
                return ResourceManager.GetString("RecordPokegearNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0063.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0061.
        /// </summary>
        internal static string ReleaseAll {
            get {
                return ResourceManager.GetString("ReleaseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0065.
        /// </summary>
        internal static string RemovePeople {
            get {
                return ResourceManager.GetString("RemovePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AF.
        /// </summary>
        internal static string ResetScreen {
            get {
                return ResourceManager.GetString("ResetScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0052.
        /// </summary>
        internal static string RestartMusic {
            get {
                return ResourceManager.GetString("RestartMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001B.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0003.
        /// </summary>
        internal static string Return2 {
            get {
                return ResourceManager.GetString("Return2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001E.
        /// </summary>
        internal static string SetFlag {
            get {
                return ResourceManager.GetString("SetFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0153.
        /// </summary>
        internal static string SetOverworldPosition {
            get {
                return ResourceManager.GetString("SetOverworldPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0029.
        /// </summary>
        internal static string SetVar {
            get {
                return ResourceManager.GetString("SetVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C0.
        /// </summary>
        internal static string SetVariableAlter {
            get {
                return ResourceManager.GetString("SetVariableAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C5.
        /// </summary>
        internal static string SetVariableAttack {
            get {
                return ResourceManager.GetString("SetVariableAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C4.
        /// </summary>
        internal static string SetVariableAttackItem {
            get {
                return ResourceManager.GetString("SetVariableAttackItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00BE.
        /// </summary>
        internal static string SetVariableHero {
            get {
                return ResourceManager.GetString("SetVariableHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C2.
        /// </summary>
        internal static string SetVariableItem {
            get {
                return ResourceManager.GetString("SetVariableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018F.
        /// </summary>
        internal static string SetVariableMoveDelete {
            get {
                return ResourceManager.GetString("SetVariableMoveDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C6.
        /// </summary>
        internal static string SetVariableNumber {
            get {
                return ResourceManager.GetString("SetVariableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C8.
        /// </summary>
        internal static string SetVariableObject {
            get {
                return ResourceManager.GetString("SetVariableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C1.
        /// </summary>
        internal static string SetVariablePokemon {
            get {
                return ResourceManager.GetString("SetVariablePokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00C7.
        /// </summary>
        internal static string SetVariablePokemonNickname {
            get {
                return ResourceManager.GetString("SetVariablePokemonNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00CA.
        /// </summary>
        internal static string SetVariablePokemonStored {
            get {
                return ResourceManager.GetString("SetVariablePokemonStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00BF.
        /// </summary>
        internal static string SetVariableRival {
            get {
                return ResourceManager.GetString("SetVariableRival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0071.
        /// </summary>
        internal static string ShowMoney {
            get {
                return ResourceManager.GetString("ShowMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0258.
        /// </summary>
        internal static string StartFriendPark {
            get {
                return ResourceManager.GetString("StartFriendPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0051.
        /// </summary>
        internal static string StopMusic {
            get {
                return ResourceManager.GetString("StopMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01DA.
        /// </summary>
        internal static string StopTrade {
            get {
                return ResourceManager.GetString("StopTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01FF.
        /// </summary>
        internal static string StoreFriendParkResult {
            get {
                return ResourceManager.GetString("StoreFriendParkResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018B.
        /// </summary>
        internal static string StoreMoveDelete {
            get {
                return ResourceManager.GetString("StoreMoveDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01D5.
        /// </summary>
        internal static string StoreMoveRem {
            get {
                return ResourceManager.GetString("StoreMoveRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015F.
        /// </summary>
        internal static string StorePokemonMenu {
            get {
                return ResourceManager.GetString("StorePokemonMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0162.
        /// </summary>
        internal static string StorePokemonNumber {
            get {
                return ResourceManager.GetString("StorePokemonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00DE.
        /// </summary>
        internal static string StoreStarter {
            get {
                return ResourceManager.GetString("StoreStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0054.
        /// </summary>
        internal static string SwitchMusic {
            get {
                return ResourceManager.GetString("SwitchMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005A.
        /// </summary>
        internal static string SwitchMusic2 {
            get {
                return ResourceManager.GetString("SwitchMusic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007E.
        /// </summary>
        internal static string TakeItem {
            get {
                return ResourceManager.GetString("TakeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0319.
        /// </summary>
        internal static string TakeMomMoney {
            get {
                return ResourceManager.GetString("TakeMomMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006F.
        /// </summary>
        internal static string TakeMoney {
            get {
                return ResourceManager.GetString("TakeMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0042.
        /// </summary>
        internal static string TextScriptMulti {
            get {
                return ResourceManager.GetString("TextScriptMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02EF.
        /// </summary>
        internal static string TextScriptMulti4 {
            get {
                return ResourceManager.GetString("TextScriptMulti4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01D9.
        /// </summary>
        internal static string TradeChosenPokemon {
            get {
                return ResourceManager.GetString("TradeChosenPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00D5.
        /// </summary>
        internal static string TrainerBattle {
            get {
                return ResourceManager.GetString("TrainerBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0039.
        /// </summary>
        internal static string TypeMessageBox {
            get {
                return ResourceManager.GetString("TypeMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0141.
        /// </summary>
        internal static string VermillionGymAnimation {
            get {
                return ResourceManager.GetString("VermillionGymAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0142.
        /// </summary>
        internal static string VermillionGymBin {
            get {
                return ResourceManager.GetString("VermillionGymBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0032.
        /// </summary>
        internal static string WaitButton {
            get {
                return ResourceManager.GetString("WaitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004D.
        /// </summary>
        internal static string WaitCry {
            get {
                return ResourceManager.GetString("WaitCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0137.
        /// </summary>
        internal static string WaitDoor {
            get {
                return ResourceManager.GetString("WaitDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004B.
        /// </summary>
        internal static string WaitFanfare {
            get {
                return ResourceManager.GetString("WaitFanfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005F.
        /// </summary>
        internal static string WaitMovement {
            get {
                return ResourceManager.GetString("WaitMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00B0.
        /// </summary>
        internal static string Warp {
            get {
                return ResourceManager.GetString("Warp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00F0.
        /// </summary>
        internal static string WarpLift {
            get {
                return ResourceManager.GetString("WarpLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A6.
        /// </summary>
        internal static string WFC {
            get {
                return ResourceManager.GetString("WFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00B3.
        /// </summary>
        internal static string WFC1 {
            get {
                return ResourceManager.GetString("WFC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0098.
        /// </summary>
        internal static string Wifi {
            get {
                return ResourceManager.GetString("Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02BD.
        /// </summary>
        internal static string WildBattle2 {
            get {
                return ResourceManager.GetString("WildBattle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00F3.
        /// </summary>
        internal static string WirelessBattleWait {
            get {
                return ResourceManager.GetString("WirelessBattleWait", resourceCulture);
            }
        }
    }
}
